language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ranajoy27/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ranajoy27/docker-react npm run test 

deploy: 
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-933366414376"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"